spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: group-id
      auto-offset-reset: earliest

  datasource:
    url: jdbc:mysql://localhost:3306/producer_consumer
    username: root
    password: Arjun123@
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format_sql: true
          dialect: org.hibernate.dialect.MySQL8Dialect

server:
    port: 8081


logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type: trace